### ISSUE TITLE
我知道你会进来看的

### ISSUE THREAD

**Issue by caicourtier** [caicourtier/caicourtier#1]
# If they cut off one head, two more shall take it's place

互联网是具有记忆的，在你嘴硬不认怂的时候，你的信息就已经永远存留在互联网上，就注定了这个结局.

感谢你把我推特小号举报到冻结消除，我求之不得，只是没想到不到2个小时你就找到了，所以找到这只会更快吧。

口口声声说什么先骂人的死全家，我暂且蒙在你满嘴喷粪的推特里。你这样的人我见多了，既然怀揣立场，就别一天到晚的把“客观”放在嘴上。

再说，实名上网不就是ccp的夙愿嘛，我只是帮他们踩一脚油门，让你成为先驱而已。

随时欢迎你的认怂

**Comment by courtiercai** [comment]
开玩笑，
1，你自己看看谁先骂人的，谁先骂粉俎的。我很少评论reddit那个号我注册3年，你check我的历史，几十条？其他我都很少评论
2，我没有装客观，我本意是让china_rl防区本来就是虎扑的一部分延伸，不希望在意识形态决战的。我写的是什么呢？
以色列 英国的事情你现在看看我那个时候是不是客观了？现在是不是起来了？我本意就是希望不要疫苗引战这交给科学家。
3，你的信息很多都是错的，而且你会freesgk开盒我也知道freesgk之前团队有人不满一些的作法离开了，我删除我的号，有一点你说对了，我不应该骂人，所以我删除我的号不是为了怕你，而是因为我觉得你们骂就骂无所谓，为什么要狗咬狗呢？
4，你最后看看你冒充我的号做了什么？嘲讽水灾，骂别人死妈，公布别人信息。chongtv的管理都不耻了吧

最后，我实名上网是因为我很peace，但是，正如我跟你说，你冒充我的号你去骂灾民，骂人死妈，现在轮到我来track你了。
任何东西都有痕迹的，你想让我不track很简单，你不管冒充谁的号请不要动不动就骂人 粉俎，死妈，什么xxx，不然慢慢钓，对了你想要更多信息欢迎跟我私信，我说过只要你能客观，我愿意公正对待，至少我承认你一点是对的吗，就是别人骂你觉得没什么在网络上先跑，不要引战这个我承认是对的，但是你不一样，你愿意改，我愿意跟你谈。

随时欢迎你改变，改掉动不动粉俎 死妈之类的

**Comment by courtiercai** [comment]
对了，对了，你冒充我的号，别骂人死妈，别骂人粉俎，别骂人ok？如果政府有做不对的，你就写朴实的文字写出来，客观一点不客观也行你可以站在你的立场，列12345，我会看得到的。如果列得好，我给你表扬转发点赞。别动不动骂人死妈 支畜啊，写出来我慢慢看，我就在这跟你交流

**Comment by caicourtier** [comment]
`我跟一些abc交流从来只是交流，没有任何的三字经，更不敢谈人肉`

https://imgur.com/a/HLCXPEp/

差不多得了，又当又立的。客观，客观你妈了个逼。你是记不得你做过啥了？

很喜欢蔡朝臣的一句话“我敢实名呢，你呢? 亮出来！”

咋真的给你实名了你就怕了？反正不能对你造成一丝损失是吧？（除了一瞬消除的十万乃至九万实名账号，甚至不惜发赌博信息逼着v2ex站长删号）

出了事就删评论删号装没做过，然后继续装客观，这点和你的支那共产党倒是绝配。

`冒充别人 嘲笑天灾 这不是人做的`

很喜欢b站网友的一句话，“本来是不应该嘲笑天灾的，可惜他们都是xx人”。

小畜生干这些事的时候你咋不劝劝呢？

翻墙都要当喷粪粉蛆的救不回来了。再说谁想跟你这种二本废物做朋友啊？瞧瞧你的推特，要是不知道还以为是个bot呢，烂图从年头发到年尾，烂梗玩不坏是吧？俺也懒得逗蛆了，你那身怂嘴硬的样子着实给你大爹们提供了巨多乐子，也恭喜你成为了典型china_irl太监标本，可能会时不时鞭尸一下，希望你不要介意。

最后给你个忠告，有立场一点都不奇怪，满嘴喷粪爱国也是你的自由。明明自己主观得一逼还嗯装中立善良无辜，真的令人恶心。提一句，写东西不是写个12345就是有逻辑了，这么爱国建议先报个写作班先把文法学好，别的不说，你那个post语无伦次看着真是辣眼睛。

`你人肉我的事情已经闹大了，只是你不知道。`

`最后留着点号记得跟我沟通，欢迎给我邮件`

一面说做朋友，一面搞威胁。就嗯吊是吧？差不多得了。🤣

**Comment by courtiercai** [comment]
我看下还能不能评论

**Comment by courtiercai** [comment]
一件事情一件事情说吧：
1，v2ex赌博信息的，是我号被盗了(因为，我不太重要的或者说无关紧要统一密码而且v2ex那个号本来就是要申请删除的)，不单单v2ex还有其他网站我都被封了几个，统一密码被漏了，后来叫v2删除我的邮件也写了，既有怕人肉冒充攻击政府，也有说我的账号泄漏了
[https://imgur.com/5TWSasz](url)


2，

**Comment by caicourtier** [comment]
> 我看下还能不能评论

谢谢，不行，这里习惯性禁止评论，简称“习禁评”
